name: "Hello World workflow"

#Controls when the action will run. Triggers the workflow on push or pull request events but only for the main branch or production branch
on:
  push:
    branches:
      - main
      - production
      - "**" # This will trigger the workflow for any branch, you can remove this line if you only want to trigger on specific branches

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World"

      - name: "Print current date"
        run: date
