name: "Multi event pipeline/workflow"

on:
  push: #Event: whenever there is a push to the repository in main branch, this workflow will be triggered
    branches:
      - main
      - test

jobs:
  on_push: #JOB NAME
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World on push"
        run: echo "Hello World on push event"
